"use client";

import { Town, MetricType } from "@/types";

interface PrintableViewProps {
  town: Town;
  comparisonTowns: Town[];
  metric: MetricType;
}

function formatMetricLabel(metric: MetricType): string {
  switch (metric) {
    case "absolute":
      return "Absolute Dollars";
    case "per_capita":
      return "Per Capita";
    case "per_road_mile":
      return "Per Road Mile";
    case "per_valuation":
      return "Per $1K Valuation";
    default:
      return "Absolute Dollars";
  }
}

export default function PrintableView({
  town,
  comparisonTowns,
  metric,
}: PrintableViewProps) {
  const now = new Date();
  const formattedDate = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const formattedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const townNames =
    comparisonTowns.length > 0
      ? `${town.name} vs ${comparisonTowns.map((t) => t.name).join(", ")}`
      : town.name;

  return (
    <>
      {/* Print Header - hidden on screen, visible when printing */}
      <div className="print-title hidden print:block print:mb-6 print:pb-4 print:border-b print:border-gray-300">
        <h1 className="text-2xl font-bold text-center mb-2">
          TownBench Municipal Budget Report
        </h1>
        <p className="text-xl text-center mb-1">{townNames}</p>
        <p className="text-sm text-center text-gray-600">
          {town.state} | Metric: {formatMetricLabel(metric)} | Generated: {formattedDate} at {formattedTime}
        </p>
      </div>

      {/* Print Footer - hidden on screen, visible when printing */}
      <div className="print-footer hidden">
        Generated by TownBench | {formattedDate} | {townNames}
      </div>
    </>
  );
}
