"use client";

import { Town, MetricType } from "@/types";

interface PrintableViewProps {
  town: Town;
  comparisonTowns: Town[];
  metric: MetricType;
}

function formatMetricLabel(metric: MetricType): string {
  switch (metric) {
    case "absolute":
      return "Absolute Dollars";
    case "per_capita":
      return "Per Capita";
    case "per_road_mile":
      return "Per Road Mile";
    case "per_valuation":
      return "Per $1K Valuation";
    default:
      return "Absolute Dollars";
  }
}

export default function PrintableView({
  town,
  comparisonTowns,
  metric,
}: PrintableViewProps) {
  const now = new Date();
  const formattedDate = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const formattedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const townNames =
    comparisonTowns.length > 0
      ? `${town.name} vs ${comparisonTowns.map((t) => t.name).join(", ")}`
      : town.name;

  return (
    <>
      {/* Print Header - only visible when printing */}
      <div className="print-header hidden">
        <h1 style={{ fontSize: "24px", fontWeight: "bold", marginBottom: "8px" }}>
          TownBench Municipal Budget Report
        </h1>
        <p style={{ fontSize: "18px", marginBottom: "4px" }}>{townNames}</p>
        <p style={{ fontSize: "14px", color: "#666" }}>
          {town.state} | Metric: {formatMetricLabel(metric)} | Generated: {formattedDate} at {formattedTime}
        </p>
      </div>

      {/* Print Footer - only visible when printing */}
      <div className="print-footer hidden">
        Generated by TownBench | {formattedDate} | {townNames}
      </div>
    </>
  );
}
